import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

// FONT CONFIGURATION
// Mengkonfigurasi font Geist Sans dari Google Fonts
const geistSans = Geist({
  variable: "--font-geist-sans", // CSS variable untuk font sans-serif
  subsets: ["latin"], // Subset karakter yang dimuat (latin untuk bahasa Eropa)
});

// Mengkonfigurasi font Geist Mono (monospace) dari Google Fonts
const geistMono = Geist_Mono({
  variable: "--font-geist-mono", // CSS variable untuk font monospace
  subsets: ["latin"], // Subset karakter yang dimuat
});

// METADATA CONFIGURATION
// Metadata untuk SEO dan browser tab
export const metadata: Metadata = {
  title: "Create Next App", // Judul yang muncul di browser tab
  description: "Generated by create next app", // Deskripsi untuk SEO
};

// ROOT LAYOUT COMPONENT
// Layout utama yang membungkus semua halaman di aplikasi
export default function RootLayout({
  children, // Konten halaman yang akan di-render
}: Readonly<{
  children: React.ReactNode; // Type untuk React children
}>) {
  return (
    <html lang="en"> {/* HTML root dengan bahasa Inggris */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        // className menggabungkan:
        // - geistSans.variable: CSS variable untuk font sans
        // - geistMono.variable: CSS variable untuk font mono
        // - antialiased: Tailwind class untuk smooth font rendering
      >
       {/* PROVIDERS WRAPPER */}
       {/* Providers membungkus app dengan SessionProvider untuk NextAuth */}
       <Providers>
          {children} {/* Konten halaman akan di-render di sini */}
        </Providers>
      </body>
    </html>
  );
}

/*
PENJELASAN KONSEP:

1. NEXT.JS LAYOUT:
   - RootLayout adalah layout utama yang membungkus semua halaman
   - Setiap halaman akan di-render sebagai 'children'
   - Layout ini akan selalu ada di setiap halaman

2. FONT OPTIMIZATION:
   - Next.js otomatis mengoptimasi Google Fonts
   - Font dimuat saat build time, bukan runtime
   - CSS variables memungkinkan penggunaan font di seluruh app

3. PROVIDERS PATTERN:
   - Providers membungkus app dengan context (SessionProvider)
   - Memungkinkan semua komponen akses ke session data
   - Pattern umum untuk state management global

4. METADATA:
   - Digunakan untuk SEO dan browser information
   - Next.js otomatis inject ke <head> tag
   - Bisa di-override di halaman individual
*/
